services:

    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    eight.pages:
        class: Eight\PageBundle\Entity\PageRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments: ['Eight\PageBundle\Entity\Page']
        public: true

    eight.tags:
        class: Eight\PageBundle\Entity\TagRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments: ['Eight\PageBundle\Entity\Tag']

    eight.blocks:
        class: Eight\PageBundle\Entity\BlockRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments: ['Eight\PageBundle\Entity\Block']
        public: true

    eight.content:
        class: Eight\PageBundle\Entity\BlockRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments: ['Eight\PageBundle\Entity\Content']
        public: true

