easy_admin:
    entities:
        Pages:
            class: Eight\PageBundle\Entity\Page
            form:
                fields:
                    - title
                    - description
                    -
                        property: locale
                        type: text
                        type_options:
                            mapped: false
                    -
                        property: url
                        type: text
                    -
                        property: controller
                        type: text
                        type_options:
                            mapped: false

                    - layout
                    - published
                    - tags
                    - sitemap
                    - sitemap_priority
                    - sitemap_change
            list:
                actions: ['layout', 'clone']
                fields:
                    - title
                    - route
                    - route.path
                    - route.locale
                    - published
                    - tags
        Tags:
            class: Eight\PageBundle\Entity\Tag