services:

    text.widget:
        class: Eight\PageBundle\Widget\Text
        tags:
            - { name: eight_page.widget }

    text_with_image.widget:
        class: Eight\PageBundle\Widget\ImageText
        tags:
            - { name: eight_page.widget }

    h1.widget:
        class: Eight\PageBundle\Widget\H1
        tags:
            - { name: eight_page.widget }

    label.widget:
        class: Eight\PageBundle\Widget\Label
        tags:
            - { name: eight_page.widget }

    header.widget:
        class: Eight\PageBundle\Widget\Header
        tags:
            - { name: eight_page.widget }

    navbar_item.widget:
        class: Eight\PageBundle\Widget\NavItem
        tags:
            - { name: eight_page.widget }

    navbar_item_ext.widget:
        class: Eight\PageBundle\Widget\NavItemExt
        tags:
            - { name: eight_page.widget }

    navbar_dropdown.widget:
        class: Eight\PageBundle\Widget\NavbarDropdown
        tags:
            - { name: eight_page.widget }

    navbar_dropdown_item.widget:
        class: Eight\PageBundle\Widget\NavbarDropdownItem
        tags:
            - { name: eight_page.widget }

    navbar_dropdown_item_ext.widget:
        class: Eight\PageBundle\Widget\NavbarDropdownItemExt
        tags:
            - { name: eight_page.widget }

    navbar_dropdown_divider.widget:
        class: Eight\PageBundle\Widget\NavbarDropdownDivider
        tags:
            - { name: eight_page.widget }

    column.widget:
        class: Eight\PageBundle\Widget\Column
        tags:
            - { name: eight_page.widget }

    one_column.widget:
        class: Eight\PageBundle\Widget\OneColumn
        tags:
            - { name: eight_page.widget }

    two_columns.widget:
        class: Eight\PageBundle\Widget\TwoColumns
        tags:
            - { name: eight_page.widget }

    two_columns_1_2.widget:
        class: Eight\PageBundle\Widget\TwoColumns_1_2
        tags:
            - { name: eight_page.widget }

    three_columns.widget:
        class: Eight\PageBundle\Widget\ThreeColumns
        tags:
            - { name: eight_page.widget }

    menu.widget:
        class: Eight\PageBundle\Widget\Menu
        tags:
            - { name: eight_page.widget }

    footer.widget:
        class: Eight\PageBundle\Widget\Footer
        tags:
            - { name: eight_page.widget }

    template.widget:
        class: Eight\PageBundle\Widget\Template
        tags:
            - { name: eight_page.widget }

    controller.widget:
        class: Eight\PageBundle\Widget\Controller
        tags:
            - { name: eight_page.widget }

    page_link.widget:
        class: Eight\PageBundle\Widget\PageLink
        tags:
            - { name: eight_page.widget }

